<?php
/**
 * @description Popup template
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 */
?>

<?php
/**
 * @var \D3p1\Popup\Block\Widget\Popup $block
 */
?>

<?php if (!$block->getShowOnInit()): ?>
    <?php
    /**
     * @note Init button
     * @note If popup is not show on page initialization then it is necessary
     *       to create a button to be able to show the popup on its click event
     */
    ?>
    <a id="<?= $block->getButtonId() ?>" class="button popup-button action primary" href="#">
        <span><?= $block->getButtonTitle() ?></span>
    </a>
<?php endif; ?>

<div class="popup-widget-container" id="<?= $block->getElementId() ?>">
    <div class="popup-content">
        <?= $block->getContentHtml() ?>
    </div>
</div>

<script type="text/javascript">
// <![CDATA[
require(['jquery', 'Magento_Ui/js/modal/modal'], function($, modal) {
    <?php
    /**
     * Init popup
     *
     * @returns {void}
     * @private
     */
    ?>
    function _initPopup() {
        var options = {
            type      : 'popup',
            responsive: true,
            title     : '<?= $block->getTitle() ?>',
            modalClass: 'popup <?= $block->getCssClass() ?>',
            buttons   : []
        };

        modal(options, $('#<?= $block->getElementId() ?>'));
    }

    $(document).ready(function() {
        _initPopup();

        <?php if ($block->getShowOnInit()): ?>
            $('#<?= $block->getElementId() ?>').modal('openModal');
        <?php else: ?>
            $('#<?= $block->getButtonId() ?>').click(function() {
                $('#<?= $block->getElementId() ?>').modal('openModal');
            });
        <?php endif; ?>
    });
});
// ]]>
</script>

